openapi: 3.0.0
info:
  title: Assignment Week 10 API
  version: 1.0.0
  description: 'This is a Week 10 - Assignment making CRUD for Transaction'
servers:
  - url: ''
    description: 'Web Access'
  - url: 'http://localhost:3000'
    description: 'Local host server''
paths:
  /user/register:
    post:
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
                - username
                - password
                - role
      responses:
        '200':
          description: User registered successfully
  /user/login:
    post:
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: User logged in successfully
  /transfer:
    get:
      summary: Get all transfers
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of all transfers
    post:
      summary: Create a transfer
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                currency:
                  type: string
                sourceAccount:
                  type: string
                destinationAccount:
                  type: string
              required:
                - amount
                - currency
                - source account
                - destination account
      responses:
        '200':
          description: Transfer created successfully
  /:
    patch:
      summary: Update approval status
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Approval status updated successfully
  /transfer/{transferId}:
    patch:
      summary: Update transfer status
      security:
        - BearerAuth: []
      parameters:
        - name: transferId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Transfer status updated successfully
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
